EddieHinojosa/Cocktail-Directory

public/css/style.css, views/drink-search.hbs
=> fixed a gap in the design that was driving me nuts

server.js, views/drink-details.hbs, views/drink-results.hbs, views/layouts/index.hbs, views/partials/drink-card.hbs
-added drink card to drink results
=> drink results

public/css/style.css, public/css/userdrinks.css, public/js/drink-search.js, server.js, views/layouts/main.hbs, views/partials/nav-bar.hbs, views/users.hbs
Made guest link close the modal
=> Guest Link

db/drinkrecipes.sql, models/User.js
updated drinkrecipes table with new columns for revised criteria.
=> database changes

models/Drinks.js, routes/users.js, views/users.hbs
added Drinks.js model for use in drink search
updated users.hbs
added dependencies to users.js file
=> users updates / model changes

public/js/drink-search.js, routes/main-routes.js, server.js, views/partials/logo.hbs
Modal wasn't closing when guest checkout was clicked, had to fix.
=> fixed guest checkout

public/js/drink-search.js, routes/search.js, routes/users.js, server.js, views/partials/drink-card.hbs
added button to drink-cards to trigger details view
added drinks.js file to handle routes for details only.
moved drink search to it's own page for easier use
=> drink details page

views/partials/nav-bar.hbs
fixed another issue with user add function.
Button looking for incorrect page. fixed and tested.
=> User add function

routes/drinks.js, server.js, views/drink-details.hbs, views/partials/drink-card.hbs
added drinks.js route to handle route for drink details display
added drink detail app.use for correct routes
updated drink-details.hbs to display basic info for cocktail
removed button and added corrected button with href link to pass data needed for drink details
=> drink details

views/drink-details.hbs, views/partials/drink-card.hbs
added comments and clarity for ratings system
=> IVIonsters Designs V1.1

routes/drinks.js, server.js, views/drink-details.hbs, views/partials/drink-card.hbs
added additional feature and fixed bugs with drink images not rendering onto drink details page.
NOTE: Drink images rendering at full size need to address that bug next.
=> Bug Fix - drink-details

public/css/style.css, views/drink-details.hbs
on css sheet and drink details page
=> changed class name

public/css/style.css, routes/main-routes.js, views/about.hbs, views/drink-details.hbs, views/profile.hbs
=> Comment Boxes

public/js/drink-search.js, routes/search.js, views/drink-search.hbs
added functionality to the slider to allow bitter or sweet preferences.
Makes adjustment based of "IF" input provided and references columns in the table for bitter and sweet looking for true false values. Op.like used for spirit type and keyword to make it more open to interpretation.
=> slider updated

models/Drinks.js, public/js/drink-search.js, routes/search.js
modified search input updates to with new model, converted to work with database not local and usable on render.
adjusted query for true false values on slider to be able to trigger new table columns and return correct boolean values for query
=> search input updates

models/Favorites.js, public/js/drink-results.js, routes/main-routes.js, views/profile.hbs
=> Favorites fully up and running. did some debugging in regards to

server.js
=> changed to strict

models/Drinks.js, package-lock.json, routes/drinks.js, routes/search.js
fixed error with drink recipes where the entire database would not seed due to text constraints. Error fixed.
Commented out console.log on certain parts to prevent terminal overload
=> Bug Fixes: drinkrecipes

public/css/style.css, views/add.hbs, views/drink-details.hbs
- Added social media buttons to drink details card
=> Social Media Buttons

config/database.js, config/passport-config.js, public/js/login-script.js, routes/auth-routes.js, routes/main-routes.js, server.js, utility/auth.js, views/partials/modal.hbs, views/partials/nav-bar.hbs
cleaned up code, added comments to login/authentication code, adjusted login/registration modal.
=> adjusted modal

models/Comment.js, public/css/style.css, routes/main-routes.js, views/add.hbs, views/drink-details.hbs, views/drink-search.hbs, views/partials/drink-card.hbs
commit a49094b8ad9adbf64b41ec0bf32a2d484218f800
Author: Clarissa Mobley <clarissamobley@me.com>
Date:   Fri Jun 14 16:42:06 2024 -0400
made add form responsive to screens
commit c62c9b62fd13070e2d48fe271594d79b322e65b9
Author: Clarissa Mobley <clarissamobley@me.com>
Date:   Fri Jun 14 16:29:55 2024 -0400
made sure drink result content was the same size and responsive to all screens
commit e63386c36ff804c2e8ce6cd495d660b0cec133ec
Author: Clarissa Mobley <clarissamobley@me.com>
Date:   Fri Jun 14 16:21:22 2024 -0400
made sure drink search content looked good on all screens
commit bc978de683e4f626be40daf94955023b07cc742b
Author: Clarissa Mobley <clarissamobley@me.com>
Date:   Fri Jun 14 16:15:38 2024 -0400
cleaned up css code
commit 5ee188e448c876fa06482d889ab5bad6c56b50e7
Author: Clarissa …
=> Squashed commit of the following:

views/profile.hbs
changed the script tag on profile.hbs to favorites.js
=> Devon branch2
